### ISSUE TITLE
Question not issue: how to add new package to homeassistant wheels

### ISSUE THREAD

**Issue by tongaimaramba** [home-assistant/wheels#160]
Hi there,

I'm working on a project for my Homeassistant set-up with the GPIO on a remote RPI. 

I've failed to install a package through the config file of Appdaemon, because the package was not found in the wheels index.

I'd like to add the packaage to the index and would appreciate some direction how to do that.

Here is info about the package: https://pypi.org/project/rpi-ws281x/#modal-close

>>>

And below is my current set-up

-----------------------------------------------------------
 Add-on: AppDaemon 4
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.3.2
 You are running the latest version of this add-on.
 System: HassOS 4.17  (armv7 / raspberrypi4)
 Home Assistant Core: 0.118.5
 Home Assistant Supervisor: 2020.12.7

>>>

And my Appdaemon config:
--
system_packages:
  - python3-dev
python_packages:
  - gpiozero
  - pigpio
  - adafruit-blinka
  - adafruit-circuitpython-neopixel
  - rpi.gpio
init_commands: []
log_level: debug
--
Note: when I add rpi-ws281x to the "python_packages:" it causes Appdaemon to crash.

Many thanks,
Tongai

**Comment by frenck** [comment]
We supply packages for Home Assistant and Home Assistant integrations, not AppDaemon.

You could suggest asking the AppDaemon to run a similar thing?

**Comment by Otiel** [comment]
@tongaimaramba Have you succeeded in using GPIO from Home Assistant?
