### ISSUE TITLE
Some wheels are not working due to wrong arch perhaps?

### ISSUE THREAD

**Issue by aptalca** [home-assistant/wheels#267]
Hi,

We're using your wheel repo to pull the wheels into our alpine 3.14 based docker image. We recently noticed that some of the wheels are not working when installed from your repo, but they work when the same version is built locally.

The list so far includes `psycopg2`, `ciso8601` and `pycares` (and growing as users report issues).

I noticed that you strip the arch from all your wheel names, so they are all listed as `*-cp39-none-any.whl`. Any specific reason for that? It would be much easier to identify arch mismatch if the wheels retained their original naming scheme like `*-cp39-cp39-linux_armv7l.whl`

I also noticed that your alpine 3.13 repo contains a bunch of wheels for `cp39` but the python version for 3.13 is `3.8` so they are simply ignored on a 3.13 based system. Just fyi.

Thanks

**Comment by frenck** [comment]
> I noticed that you strip the arch from all your wheel names, so they are all listed as *-cp39-none-any.whl. Any specific reason for that?

We use a different repo for each arch, so that is not a concern for us.

> I also noticed that your alpine 3.13 repo contains a bunch of wheels for cp39 but the python version for 3.13 is 3.8 so they are simply ignored on a 3.13 based system. Just FYI.

We use our own Python versions, not the ones from Alpine.

Please note, these wheel repositories are specifically tailored to our use cases and not meant for a public solution for other projects.
