### ISSUE TITLE
armv7 loop restart

### ISSUE THREAD

**Issue by magicse** [home-assistant/wheels#512]
- Host system Ubuntu64 x86
- Target arch  armv7
- final system Docker QNAP armv7
- Base image repo https://github.com/home-assistant/core
- To eliminate the influence of already created Wheels from repo "https://wheels.home-assistant.io/musllinux/", I changed the Dockerfile.  - [Changed Dockerfile](https://github.com/home-assistant/core/issues/86589#issuecomment-1445029885)
- Build commands for cross-build.

```
git clone https://github.com/home-assistant/core.git 03.hass-core
cd 03.hass-core
docker buildx build --output type=docker --platform linux/arm/v7 --build-arg BUILD_FROM=ghcr.io/home-assistant/armv7-homeassistant-base:2023.02.0 --build-arg QEMU_CPU=cortex-a15 .
```
- Result waiting - building in progress

_Originally posted by @magicse in https://github.com/home-assistant/core/issues/86589#issuecomment-1445441363_

**Comment by frenck** [comment]
This is now the second time I have to ask you to stop the cross posting issue.

Closing this, please track the issue in core instead.

../Frenck

**Comment by magicse** [comment]
Hello. I'm sorry.
